<a href="https://colab.research.google.com/github/Pradhibha/CHATBOT/blob/master/PNB_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Practice Notebook

### Introduction to Numpy
NumPy (Numerical Python) is a python library for scientific computing, that provides high-performance vectors, matrices and higher-dimensional data structures for Python.

## Numpy

####  Exercise 1: Import the numpy package as np.

Hint: use 'import … as …'

In [12]:
# YOUR CODE HERE
import numpy as np

####  Exercise 2: Print the numpy version and the configuration.

Hint: np.__version__, np.show_config

In [2]:
# YOUR CODE HERE
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
<function show at 0x7e28cfb90820>


#### Exercise 3: Create an array of 10 zeros and 20 ones.

Hint: np.zeros, np.ones

In [64]:
# YOUR CODE HERE
np.zeros(10,dtype='int')
np.ones(10,dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

####  Exercise 4: Create a vector with values ranging from 10 to 49.

Hint: np.arange

In [7]:
# YOUR CODE HERE
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

####  Exercise 5: Reverse a vector (first element becomes last).

Hint: np.array[::-1]

In [66]:
# YOUR CODE HERE
a=np.arange(10)
print(a)
print(a[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


####  Exercise 6: Find the indices of the non-zero elements from [1, 2, 0, 0,  4, 0].

Hint: np.nonzero

In [19]:
# YOUR CODE HERE
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

####  Exercise 7: Create a 3x3 identity matrix.

Hint: np.eye

In [25]:
# YOUR CODE HERE
np.eye(4,4,k=3,dtype=int)

array([[0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### Exercise 7: Generate a random number between 0 and 1 using numpy.

Hint: np.random.rand()

In [27]:
# YOUR CODE HERE
np.random.rand()

0.26286304219567347

####  Exercise 8: Create a 10x10 array with random values, find the minimum and the maximum values.

Hint: min, max

In [33]:
# YOUR CODE HERE
x=np.random.random((5,5))
print(x)
print(x.min())
print(x.max())


[[0.54347134 0.30163465 0.04122278 0.54627846 0.85283497]
 [0.27129002 0.00948473 0.67606023 0.19904984 0.78730433]
 [0.52635165 0.30653448 0.68496946 0.80895626 0.18070138]
 [0.84006472 0.25288586 0.73294595 0.73243122 0.16039583]
 [0.53053115 0.29310882 0.44902107 0.11513483 0.41941914]]
0.009484725338233746
0.8528349711526368


####  Exercise 9: Create a numpy array from the given `List`.

Hint: np.array

In [37]:
# YOUR CODE HERE
np.array([[1,2,3,4,5,6,7],[1,2,1,1,2,2,2]])

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 1, 1, 2, 2, 2]])

####  Exercise 10: Matrix multiplication for 1-D array.

To multiply the matrix a and b.

Hint: np.dot

In [38]:
a = np.array([9, 5, 7, 4])
b = np.array([9, 5, 4, 3])

# YOUR CODE HERE
np.dot(a,b)

146

####  Exercise 11: Transpose the given array [ [ 1, 2, 3], [ 4, 5, 6],  [ 7, 8, 9], [10, 11, 12] ].
Hint: np.transpose( )

In [39]:
# YOUR CODE HERE
np.transpose([ [ 1, 2, 3], [ 4, 5, 6], [ 7, 8, 9], [10, 11, 12] ])

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

####  Exercise 12: Given an array *A*, calculate the square root of the elements in it.

Hint: np.sqrt( )

In [43]:
A = np.arange(1,20)
print(A)
print(np.sqrt(A))
# YOUR CODE HERE

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894]


#### Exercise 13: Concatenate two numpy arrays columnwise  by specifying axis = 1.
Hint: np.concatenate( )

In [45]:
c =np.array([[1,2],[3,4]])
d =np.array([[5,6],[7,8]])
# YOUR CODE HERE
np.concatenate((c,d),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### Exercise 14: Print the second and the third column for the given multidimensional array.


In [49]:
a = np.array([[2, 4, 6, 8, 10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])
# YOUR CODE HERE
print(a[:,2:4])

[[ 6  8]
 [ 9 12]
 [12 16]]


####  Exercise 15: For the given multidimensional array:
1. Calculate the mean row wise by specifying axis = 0 and column wise by specifying axis =1.
2. What is the average value of an array?

In [54]:
# 2D array
arr = np.array([[2, 4, 6, 8, 10],
              [3, 6, 9, 12, 15],
              [4, 8, 12, 16, 20]])
#YOUR CODE HERE
print("\nmean of arr, axis = None : ", np.mean(arr))

# mean along the axis = 0
print("\nmean of arr, axis = 0 : ", np.mean(arr, axis = 0))

# mean along the axis = 1
print("\nmean of arr, axis = 1 : ", np.mean(arr, axis = 1))



mean of arr, axis = None :  9.0

mean of arr, axis = 0 :  [ 3.  6.  9. 12. 15.]

mean of arr, axis = 1 :  [ 6.  9. 12.]


#### Exercise 16: Create an array of all the even numbers from 30 to 70.

In [56]:
#YOUR CODE HERE
array = np.arange(30, 71, 2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### Exercise 17: For the given array, get the slice of the first row and print them.

In [59]:
a3 = np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])

#YOUR CODE HERE
print(a3[0:1,:])

[[[10 11 12]
  [13 14 15]
  [16 17 18]]]
